GET_HEADERS = {"Accept": "application/json"}
POST_HEADERS = {"Content-Type": "application/json", "Accept": "application/json"}

KEYWORDED_ARGUMENTS = {
    "register_enterprise_user": [
        "job_title",
        "company_name",
        "mobile_number",
        "user_password",
        "security_question",
        "security_answer",
        "enterprise_role",
        "email_notification",
        "country",
        "time_zone",
        "language",
        "user_ra_id",
        "user_csp_id",
        "certificate_alias",
        "common_name",
    ],
    "update_enterprise_user": [
        "user_name",
        "job_title",
        "company_name",
        "mobile_number",
        "user_old_password",
        "user_new_password",
        "security_question",
        "security_answer",
        "enterprise_role",
        "email_notification",
        "enabled",
        "country",
        "time_zone",
        "language",
        "user_ra_id",
        "user_csp_id",
        "certificate_alias",
        "common_name",
    ],
    "update_workflow_details": [
        "workflow_mode",
        "workflow_type",
        "continue_on_decline",
        "message",
    ],
    "update_workflow_user": [
        "user_email",
        "user_name",
        "role",
        "email_notification",
        "signing_order",
    ],
    "add_signature_field": [
        "field_name",
        "display",
        "x",
        "y",
        "width",
        "height",
        "level_of_assurance",
    ],
    "add_in_person_field": [
        "field_name",
        "placeholder",
        "display",
        "x",
        "y",
        "width",
        "height",
    ],
    "add_initials_field": ["field_name", "x", "y", "width", "height"],
    "update_textbox_field": [
        "renamed_as",
        "page_number",
        "page_number",
        "type",
        "format",
        "placeholder",
        "value",
        "max_length",
        "multiline",
        "field_type",
        "validation_rule",
        "font_name",
        "font_size",
        "font_embedded_size",
        "x",
        "y",
        "width",
        "height",
    ],
    "sign_document_v4": [
        "signing_reason",
        "signing_location",
        "contact_information",
        "user_name",
        "user_password",
        "appearance_design",
        "skip_verification",
    ],
    "sign_document_v3": [
        "signing_reason",
        "signing_location",
        "contact_information",
        "user_name",
        "user_password",
        "appearance_design",
        "signing_capacity",
        "witness_signing_capacity",
        "skip_verification",
    ],
    "register_user_free_trial": [
        "job_title",
        "company_name",
        "mobile_number",
        "country",
        "time_zone",
        "language",
        "service_agreements",
        "marketing_emails",
    ],
    "update_general_profile_information": [
        "user_name",
        "job_title",
        "company_name",
        "mobile_number",
        "country",
        "time_zone",
        "language",
        "user_national_id",
    ],
    "update_signature_delegation_settings": ["user_name", "user_email", "from", "to"],
    "update_personal_group": ["Name", "Description", "Members"],
    "add_groups_to_workflow": ["role", "email_notification", "signing_order"],
    "update_workflow_group": [
        "group_name",
        "role",
        "email_notification",
        "signing_order",
    ],
    "add_placeholder_to_workflow": ["role", "email_notification", "signing_order"],
    "update_placeholder": [
        "placeholder",
        "role",
        "email_notification",
        "signing_order",
    ],
    "update_enterprise_group": ["name", "description", "members"],
}
